services:
  identity-postgres:
    image: postgres:17
    container_name: pulsedelivery-identity-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password123*
      POSTGRES_DB: IdentityDb
    ports:
      - "5433:5432"
    volumes:
      - identity_postgres_data:/var/lib/postgresql/data

  order-postgres:
    image: postgres:17
    container_name: pulsedelivery-order-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password123*
      POSTGRES_DB: OrderDb
    ports:
      - "5434:5432"
    volumes:
      - order_postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: pulsedelivery-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: mongo:latest
    container_name: pulsedelivery-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  identity_postgres_data:
  order_postgres_data:
  mongo_data: